title: "Online clustering: algorithms, evaluation, metrics, application and benchmarking using River"
description: Tutorial presented at the 26<sup>th</sup> Pacific-Asia Conference on Knowledge Discovery and Data Mining (PAKDD), May 16<sup>th</sup> - 19<sup>th</sup>, 2022, Chengdu, China
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
