title: "Online clustering: algorithms, evaluation, metrics, aplication and benchmarking using River"
description: Tutorial presented at the 26th Pacific-Asia Conference on Knowledge Discovery and Data Mining (PAKDD), May 16th - 19th, 2022, Chengdu, China.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
